### ISSUE TITLE
The manager to persist the entities

### ISSUE THREAD

**Issue by john11281988** [aeviiq/storage-manager#6]
first of all thank you for this conponent!! saved us alot of work and solved some bugs!

We have 1 suggestion for the manager:
could you make it so it can optionaly persist (new) entity when saved? in some parts where we want to save and also store the entity we now have to use both this manager and also entity manager

**Comment by aeviiq** [comment]
Hi @john11281988,

In my opinion, it is not the responsibility of the storage manager to save the entities. It explicitly checks if the entity is attached to the unit of work and has defined identifiers for this very reason.

What you could do however, is add a filter  to the injected DeepCopy instance (https://github.com/myclabs/DeepCopy#filters). Combined with the already existing matcher (DoctrineEntityMatcher class in this component). In that filter you could support the logic you would like. Make sure your filter is executed **before** the ones defined in the storage manager.

This could not be done in the manager itself, because the entity could in theory be nested _n_ levels deep, hence the recursive scanning/copying that is done.

I do not recommend to handle the logic this way though. It would make more sense to handle the required logic for creating new entities, separately from saving _temporary_ data to the session.

I hope this answered your question.
